server:
  port: 9999
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul&verifyServerCertificate=false&useSSL=false
#    username: cos
#    password: cos1234
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

easyconv:
  app:
    jwtSecret: easyconvSecretKey
    jwtExpirationMs: 86400000
