server:
  port: 9999
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul&verifyServerCertificate=false&useSSL=false
#    username: cos
#    password: cos1234
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 199193145315-202bbh00tk3cso33v1u7fo8erug6e5a8.apps.googleusercontent.com
            client-secret: NQDuyreQENZ4e5pQly2DLNNY
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            client-id: 395062168334030
            client-secret: d7c206596be74ddac161c8b568a2337b
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
#          naver:
#            client-id: 8dlLeVqmSdElrLlTkxt9
#            client-secret: 4QoFyV31z5
#            scope:
#              - name
#              - email
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect_uri: http://localhost:8080/login/oauth2/code/naver
#            # redirect_uri는 Google, Facebook과 같이 프로바이더인 경우 기본적으로 붙어서 오기 때문에
#            # 명시해줄 필요가 없지만 Naver 등 국가만의 포털 사이트에서는 redirect_uri 를 명시해주어야 한다.
#            # 없기 때문에 명시
#
#        provider:
#          naver:
#            #${context-path}/oauth2/authorization/naver 를 탈 경우 리다이렉트 되는 uri
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌
